source 'https://rubygems.org'

gem 'rails', '4.0.2'
gem 'rom-rails', path: '../../'
gem 'morpher'

group :test do
  gem 'rspec-core', '~> 2.14'
  gem 'rspec-expectations', '~> 2.14'
  gem 'rspec-rails', '~> 2.14'

  gem 'rom', git: 'https://github.com/rom-rb/rom.git', branch: 'master'
  gem 'axiom-memory-adapter'
end
