# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Dummy::Application.load_tasks

require 'rom/sql/rake_task'

namespace :db do
  task :setup do
    ROM.setup(:sql, "sqlite://#{Rails.root}/db/#{Rails.env}.sqlite3")
    ROM.finalize
  end
end
