# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Dummy::Application.load_tasks

require 'rom/sql/rake_task'

require 'rspec/core/rake_task'

Rake::Task[:spec].clear

namespace :spec do
  desc "Run all specs excluding isolation specs"
  task all: [:unit, :lib, :integration, :features]
end
